version: "3.9"

services:
  db:
    image: postgres:16
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5544:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  backend:
    build:
      context: ./services/backend-python
      dockerfile: Dockerfile
    restart: unless-stopped
    depends_on:
      - db
    environment:
      BACKEND_DATABASE_URL: ${BACKEND_DATABASE_URL}
      BACKEND_DEBUG: "true"
      BACKEND_APP_NAME: "Piano Tutor AI Backend"
      BACKEND_CORS_ORIGINS: "[\"http://localhost:3000\", \"http://127.0.0.1:3000\", \"http://localhost:3001\", \"http://127.0.0.1:3001\", \"http://localhost:3100\", \"http://127.0.0.1:3100\"]"
    ports:
      - "8001:8000"
    volumes:
      - backend_storage:/app/storage
    healthcheck:
      test: ["CMD-SHELL", "python - <<'PY'\nimport urllib.request, sys\ntry:\n  with urllib.request.urlopen('http://localhost:8000/health', timeout=2) as r:\n    sys.exit(0 if r.status==200 else 1)\nexcept Exception:\n  sys.exit(1)\nPY"]
      interval: 10s
      timeout: 3s
      retries: 10
      start_period: 10s

  frontend:
    build:
      context: .
      dockerfile: apps/frontend/Dockerfile
      args:
        NEXT_PUBLIC_API_URL: ${NEXT_PUBLIC_API_URL:-http://localhost:8001}
    restart: unless-stopped
    depends_on:
      - backend
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_API_URL=http://localhost:8001
    ports:
      - "${FRONTEND_PORT:-3001}:3000"
    healthcheck:
      test: ["CMD-SHELL", "node -e \"require('http').get('http://localhost:3000', r=>process.exit(r.statusCode===200?0:1)).on('error',()=>process.exit(1))\" "]
      interval: 15s
      timeout: 3s
      retries: 10
      start_period: 15s

volumes:
  db_data:
  backend_storage:
